version: '2.4'
services:
  database:
    image: mysql:5.7
    container_name: database
    restart: always
    environment:
      MYSQL_DATABASE: ocppBatteryController
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql

  backend:
    image: org.ocpp.battery.controller:1.0.0
    container_name: ocppBatteryController
    restart: on-failure
    depends_on:
      - database
    ports:
      - "8081:8081"
    environment:
      SPRING_APPLICATION_JSON: '{
                  "spring.datasource.url": "jdbc:mysql://database:3306/ocppBatteryController"
                }'

volumes:
  database: {}
